### ISSUE TITLE
Docs not available at docs.racket-lang.org

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [ralsei/graphite#10]
Hi!

I just noticed, that the docs of graphite are not (no longer?) available on <https://docs.racket-lang.org>. <https://docs.racket-lang.org/graphite/index.html> shows an exception:

> Page not found
```scheme
([(uncaught-exception-handler)](https://docs.racket-lang.org/)
   (*(+(*)(*(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*)(*))(+(*)(*)(*)(*))))(+(*)(*)(*)(*))))
uncaught exception: 404
```

However, the package is listed in the package index at <https://pkgd.racket-lang.org/pkgn/search?q=graphite>.

Not sure if this is all as it should be, thought I should leave a note here.

**Comment by samth** [comment]
See #11
